[package]
name = "tx_proc"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
itertools = "0.10.5"

[dependencies]
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
serde = { version = "1.0.210", features = ["derive"] }
csv = "1.3.0"

